In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeroes(10)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [4]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a=np.array([2,7,9,10,11])
a

array([ 2,  7,  9, 10, 11])

In [8]:
a[3]

np.int64(10)

In [9]:
a[3] = 66
a

array([ 2,  7,  9, 66, 11])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])